### ISSUE TITLE
CORS header ‘Access-Control-Allow-Origin’ missing error

### ISSUE THREAD

**Issue by markratledge** [nrobinson2000/donate-bitcoin#3]
I'm getting a console error: https://blockchain.info/ticker?cors=true. (Reason: CORS header ‘Access-Control-Allow-Origin’ missing).

But the URL appears to be correct by using ?cors=true.

Any ideas?

**Comment by nrobinson2000** [comment]
What browser are you using?  On all the browsers I’ve used I haven’t had this error.

**Comment by markratledge** [comment]
Ah, my mistake; I forgot I had third-party scripts disabled. Works fine. Feel free to delete this issue.
